CREATE TABLE "ChatSetting" (
  "id" TEXT NOT NULL DEFAULT 'main',
  "settings" JSONB NOT NULL DEFAULT '{}',
  "version" INTEGER NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ChatSetting_pkey" PRIMARY KEY ("id")
);
ALTER TYPE "EconomyEntryType" ADD VALUE IF NOT EXISTS 'ADMIN_ADJUSTMENT';
