"use client";
import { useEffect, useState } from "react";
import { adminRequest, type EconomyRecord, type SystemState } from "@/lib/admin-api";
import { getRadioStatus, radioRequest, type RadioStatus } from "@/lib/radio-api";
export function AdminSystemPanel() {
  const [state, setState] = useState<SystemState | null>(null), [error, setError] = useState("");
  async function load() { setError(""); try { setState(await adminRequest<SystemState>("system")); } catch (cause) { setError(String(cause instanceof Error ? cause.message : cause)); } }
  useEffect(() => { void load(); }, []);
  return <section className="admin-panel"><header><h3>Состояние сервера</h3><button onClick={() => void load()}>Обновить</button></header>{error && <p role="alert" className="auth-error">{error}</p>}{state && <><dl className="admin-system-grid"><div><dt>Среда</dt><dd>{state.environment}</dd></div><div><dt>API работает</dt><dd>{Math.floor(state.uptimeSeconds / 60)} мин.</dd></div><div><dt>Запрос к БД</dt><dd>{state.databaseMs} мс</dd></div><div><dt>Память API</dt><dd>{state.memoryMb} МБ</dd></div><div><dt>Свободно на диске API</dt><dd>{state.diskFreeMb === null ? "Нет данных" : state.diskFreeMb + " МБ"}</dd></div>{Object.entries(state.modules).map(([key, value]) => <div key={key}><dt>{{ radio: "Радио", quiz: "Викторина", testBots: "Тестовые боты" }[key]}</dt><dd>{value ? "Включено" : "Отключено"}</dd></div>)}</dl><p>Ключи, SMTP-пароли и резервные копии не доступны из браузера. Модули включаются в конфигурации сервера; тестовые боты запрещены в production.</p></>}</section>;
}
export function AdminEconomyLedger({ userId }: { userId?: string }) {
  const [items, setItems] = useState<EconomyRecord[]>([]), [cursor, setCursor] = useState<string | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function load(next?: string) { setBusy(true); setError(""); try { const query = new URLSearchParams(); if (userId) query.set("userId", userId); if (next) query.set("cursor", next); const data = await adminRequest<{ items: EconomyRecord[]; nextCursor: string | null }>("economy?" + query); setItems(current => next ? [...current, ...data.items] : data.items); setCursor(data.nextCursor); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ошибка загрузки журнала"); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [userId]);
  return <section className="admin-panel"><header><h3>Журнал экономики</h3><button disabled={busy} onClick={() => void load()}>Обновить</button></header>{error && <p role="alert" className="auth-error">{error}</p>}<div className="admin-ledger">{items.map(item => <article key={item.id}><strong>{item.user.displayName}</strong><small>{new Date(item.createdAt).toLocaleString("ru-RU")} · {item.type}</small><span>Кредиты: {item.creditsDelta > 0 ? "+" : ""}{item.creditsDelta} · рейтинг: {item.ratingDelta > 0 ? "+" : ""}{item.ratingDelta} · баланс: {item.balanceAfter}</span></article>)}</div>{!items.length && !busy && <p>Операций пока нет.</p>}{cursor && <button disabled={busy} onClick={() => void load(cursor)}>Показать следующие 50</button>}</section>;
}
export function AdminRadioPanel({ onStudio }: { onStudio: () => void }) {
  const [status, setStatus] = useState<RadioStatus | null>(null), [price, setPrice] = useState(5), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { void getRadioStatus().then(next => { setStatus(next); setPrice(next.price); }).catch(cause => setError(cause.message)); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { await radioRequest("/settings", { price }, "PATCH"); const next = await getRadioStatus(); setStatus(next); setNotice("Цена заказа обновлена. Уже созданные заказы сохраняют свою цену."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось сохранить цену"); } finally { setBusy(false); } }
  return <section className="admin-panel"><h3>Музыкальный эфир</h3>{error && <p role="alert" className="auth-error">{error}</p>}{notice && <p role="status">{notice}</p>}{status && <><p>{!status.enabled ? "Модуль радио отключён в конфигурации сервера." : status.live ? "В эфире: " + (status.host?.displayName ?? "DJ") : "Эфир не запущен."}</p><form onSubmit={save}><label className="admin-operation-reason">Цена заказа, кредитов<input type="number" min={1} max={10000} required value={price} onChange={event => setPrice(event.target.valueAsNumber)} /></label><button className="action-button" disabled={busy || !status.enabled}>Сохранить цену</button></form><button className="action-button secondary" disabled={!status.enabled} onClick={onStudio}>Открыть студию и очередь заказов</button><p>Права DJ выдаются во вкладке «Пользователи». Запуск эфира, загрузка треков и решения по заказам доступны в студии.</p></>}</section>;
}
