"use client";

import { useEffect, useState } from "react";
import { ImagePlus, Plus, Trash2, Upload } from "lucide-react";
import { createPhotoAlbum, deleteAlbumPhoto, deletePhotoAlbum, getPhotoAlbums, uploadAlbumPhoto, type PhotoAlbum } from "@/lib/profile-albums-api";

export function ProfileAlbums() {
  const [albums, setAlbums] = useState<PhotoAlbum[]>([]); const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function reload() { try { setAlbums(await getPhotoAlbums()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить альбомы"); } }
  useEffect(() => { void reload(); }, []);
  async function create() { setBusy(true); setError(""); try { const album = await createPhotoAlbum(title); setAlbums((items) => [...items, album]); setTitle(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось создать альбом"); } finally { setBusy(false); } }
  async function addPhoto(albumId: string, file: File | null) { if (!file) return; setBusy(true); setError(""); try { const photo = await uploadAlbumPhoto(albumId, file); setAlbums((items) => items.map((album) => album.id === albumId ? { ...album, photos: [...album.photos, photo] } : album)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить фотографию"); } finally { setBusy(false); } }
  async function removeAlbum(albumId: string) { if (!window.confirm("Удалить альбом и все фотографии в нём?")) return; setBusy(true); setError(""); try { await deletePhotoAlbum(albumId); setAlbums((items) => items.filter((album) => album.id !== albumId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось удалить альбом"); } finally { setBusy(false); } }
  async function removePhoto(albumId: string, photoId: string) { setBusy(true); setError(""); try { await deleteAlbumPhoto(albumId, photoId); setAlbums((items) => items.map((album) => album.id === albumId ? { ...album, photos: album.photos.filter((photo) => photo.id !== photoId) } : album)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось удалить фотографию"); } finally { setBusy(false); } }
  return <section className="profile-settings-content profile-albums-content"><header><h2>Фотоальбомы</h2><p>До 2 альбомов и до 10 фотографий в каждом. Больше лимитов появится с VIP-статусом.</p></header><div className="profile-albums-body">{albums.length < 2 && <div className="album-create"><input value={title} maxLength={80} onChange={(event) => setTitle(event.target.value)} placeholder="Название альбома" /><button type="button" className="action-button" disabled={busy || !title.trim()} onClick={() => void create()}><Plus size={15} />Создать</button></div>}{error && <div className="auth-error">{error}</div>}{albums.length === 0 && <div className="albums-empty"><ImagePlus size={24} /><b>Альбомов пока нет</b><span>Создайте первый альбом для своих фотографий.</span></div>}{albums.map((album) => <article className="photo-album-card" key={album.id}><header><div><strong>{album.title}</strong><small>{album.photos.length}/10 фотографий</small></div><button type="button" className="album-delete" title="Удалить альбом" aria-label="Удалить альбом" disabled={busy} onClick={() => void removeAlbum(album.id)}><Trash2 size={15} /></button></header><div className="album-photo-grid">{album.photos.map((photo) => <figure key={photo.id}><img src={photo.thumbnailUrl} alt={photo.originalName} /><button type="button" aria-label="Удалить фотографию" title="Удалить фотографию" disabled={busy} onClick={() => void removePhoto(album.id, photo.id)}><Trash2 size={13} /></button></figure>)}{album.photos.length < 10 && <label className="album-upload"><Upload size={17} /><span>Добавить фото</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(event) => { void addPhoto(album.id, event.target.files?.[0] ?? null); event.target.value = ""; }} /></label>}</div></article>)}</div></section>;
}